In [1]:
import numpy as np

In [4]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [5]:
np.mean(grades)

np.float64(87.5)

In [6]:
np.median(grades)

np.float64(88.5)

In [7]:
np.std(grades)

np.float64(6.591661399070799)

In [8]:
np.max(grades)

np.int64(98)

In [9]:
np.min(grades)

np.int64(75)

In [10]:
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [11]:
slices = grades[-3]
print(slices)

98


In [13]:
np.sum(grades>90)

np.int64(3)

In [22]:
np.mean(grades>90)*100

np.float64(30.0)

In [23]:
np.mean(grades<75)*100

np.float64(0.0)

In [27]:
high_performer = grades[grades>90]
print(high_performer)

[92 95 98]


In [32]:
passing_grades = grades[grades>75]
print(passing_grades)

[85 90 88 92 95 80 98 89 83]
